---
variables:
  FF_NETWORK_PER_BUILD: 'true'
  PYTHON_VERSION: '3.10'
  IMAGE_NAME: aptmirror/apt-mirror2


stages:
  - security

.pip cache:
  cache:
    paths:
      - $PIP_CACHE_DIR
    when: always
  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

.security defaults:
  stage: security
  allow_failure: true
  needs: []

.test defaults:
  extends:
    - .pip cache
  image: python:$PYTHON_VERSION
  before_script:
    - pip install -r requirements.txt
  needs: []

.validate defaults:
  extends:
    - .test defaults
  stage: validate
  script:
    - >-
      "${VALIDATE_TOOL}" ${VALIDATE_TOOL_ARGS}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

security (trivy):
  extends:
    - .security defaults
  image:
    name: aquasec/trivy
    entrypoint: [""]
  script:
    - trivy --version
    - trivy fs . --debug
  cache:
    paths:
      - .trivy
    when: always
  variables:
    TRIVY_CACHE_DIR: .trivy
    TRIVY_EXIT_CODE: 1
    TRIVY_SCANNERS: vuln,config

