.Dd September 2024
.Dt apt-mirror2 1
.Sh NAME
.Nm apt-mirror2
.Nd an apt sources mirroring
tool
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl -version
.Op Ar Sy configfile
.Sh DESCRIPTION
.Nm
is the Python/asyncio reimplementation of the apt-mirror - an apt sources mirroring
tool.  
.sp 0
This project is intended to be a general drop-in apt-mirror replacement.
.sp 1
One of the main advantages of the
.Nm
over the apt-mirror is that it never leaves a broken mirror behind, provided
it exits with code 0.
This is ensured by data integrity checks at all stages of mirroring.
.sp 1
Most of apt-mirror configuration directives are supported.
.sp 0
As of now proxy for FTP repositories is not supported.
.sp 1
File lists (ALL, NEW, MD5, SHA256, SHA512) are not written by default, but you
can enable them with the write_file_lists option.
.sp 1
.Bl -dash -offset 14
In addition there are some enhancements available:
.It
Non-zero exit code is returned if some of required files were not downloaded due
to network or server errors or no repositories were configured.
.It
Flexible support for filtering by package name, source name, section, or Debtags
.It
Optional Release files GPG signature verification
.It
Repositories lacking MD5 hashes are correctly mirrored
.It
Old index files are properly cleaned and don't produce errors during the mirror
processing
.It
Standard sources.list
.Ql [ arch=arch1,arch2 ]
can be used to specify multiple repository architectures for mirroring.
multiple codenames (or flat folders) can be specified using comma as delimiter.
.It
.Ql mirror_path URL PATH
option may be used to specify PATH to use for saving mirror files instead of the
path that is generated from URL.
.It
Additional configurations are loaded from the
.Ql *.list
files in the directory named the same as the configfile with the .d suffix. Eg
.Ql /etc/apt/mirror.list.d/*.list
\&.
.It
Rate limit is enforced for overall download rate.
.It
Slow download rate protection is enabled by default and can be configured via
.Ql mirror.list
\&.
.It
HTTP user agent can be configured via user_agent configuration.
.It
Configuration variables are exposed to the postmirror_script.
.It
.Ql by-hash
list option can be used to control whether Acquire-By-Hash Release
option should be respected or enforced.
.It
Mirror wipe protection is available and configurable via
.Ql wipe_size_ratio
and
.Ql wipe_count_ratio
settings.
.It
Per-repository log files are available in the
.Ql var_path
folder
.It
The
.Ql dists
folder is replaced almost atomically using move instead of copy/link
.It
Native Prometheus metrics are supported
.It
\&... and others
.El
.sp 1
.Bl -tag -width Ds
Positional arguments:
.It Ar Sy  configfile
Path to config file. Default
.Ql /etc/apt/mirror.list
when run with the
.Ql apt-mirror
filename and
.Ql /etc/apt/mirror2.list
when run with the
.Ql apt-mirror2
filename and file
.Ql /etc/apt/mirror2.list
is exists.
.El
.sp 1
.Bl -tag -width Ds
Options:
.It Fl h, --help
show help message and exit
.It Fl -version
Show version
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev APT_MIRROR_LOGLEVEL
Log level as supported by Python logging module. Default
.Ql info
\&.
.El
.Sh FILES
.Bl -tag -width "/etc/apt/mirror2.list.d/*.list" -compact
.It Pa /etc/apt/mirror.list
Main configuration file when run with the
.Ql apt-mirror
filename
.It Pa /etc/apt/mirror.list.d/*.list
Additional configuration files when run with the
.Ql apt-mirror
filename
.It Pa /etc/apt/mirror2.list
Main configuration file when run with the
.Ql apt-mirror2
filename
.It Pa /etc/apt/mirror2.list.d/*.list
Additional configuration files when run with the
.Ql apt-mirror2
filename
.El
.Sh AUTHORS 
.An Yuri Konotopov Aq Mt ykonotopov@gnome.org
