[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "apt-mirror"
version = "17a1"
authors = [
    {name = "Yuri Konotopov", email = "ykonotopov@gnome.org"},
]
description = "apt-mirror Python reimplementation"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["apt", "debian"]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: AsyncIO",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "aiofile==3.12.3",
    "aiolimiter==1.3.0",
    "aioftp==0.28.0",
    "httpx[http2]==0.28.1",
    "python-debian==1.1.1",
]

[project.optional-dependencies]
dev = [
    "pip-tools==7.6.1",
    "pyinstaller==6.22.2",
    "pylint==4.0.8",
    "pytest==9.1.1",
    "ruff==0.16.6",
]
aiofiles = [
    "aiofiles==25.1.0"
]
prometheus = [
    "prometheus-client==0.26.0"
]
uvloop = [
    "uvloop==0.22.1",
]

[project.scripts]
apt-mirror = "apt_mirror.apt_mirror:main"

[project.urls]
Homepage = "https://gitlab.com/apt-mirror2/apt-mirror2/"
Repository = "https://gitlab.com/apt-mirror2/apt-mirror2.git"
Github = "https://github.com/nE0sIghT/apt-mirror2.git"
Issues = "https://gitlab.com/apt-mirror2/apt-mirror2/-/issues"
Changelog = "https://gitlab.com/apt-mirror2/apt-mirror2/-/commits/master/"

[tool.setuptools.packages.find]
include = ["apt_mirror*"]

[tool.pylint.main]
ignore-patterns = "^\\.#"
jobs = 0
disable = [
    "C0111",
    "W1203",
]

[tool.pyright]
exclude = [
    "build/",
    "contrib/",
    "dist/",
    "**/*.egg-info",
]

[tool.pytest.ini_options]
minversion = "7.0"
pythonpath = [
    "."
]
testpaths = [
    "tests",
]

[tool.ruff.lint.isort]
known-first-party = ["apt_mirror"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    # We don't want to replace huge `if` statements with return
    "SIM103",
    # Explicit is better than implicit
    "UP015",
]
