services:
  apt-mirror2-debian-vscode:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        DEBIAN_VERSION: '12'
    image: apt-mirror2-debian-vscode
    volumes:
      - "../:/workspace/debian:cached"
    networks:
      - apt-mirror2-debian

networks:
  apt-mirror2-debian:
